### ISSUE TITLE
Access Violation when scaning Pictures

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#102]
cannot test with alpha due to [https://github.com/salvadorbs/Asuite/issues/101](url)
![20210721010730](https://user-images.githubusercontent.com/17204819/126407089-c5ce8fa9-a71a-4486-beb8-67fd095f4cb0.PNG)

**Comment by salvadorbs** [comment]
With the resolution of #101, you should now be able to test the ScanFolder without major problems (I hope! :)). Tried it on my computer, with the Pictures folder and had no problems.

P.S .: ASuite 2.0 was developed using Delphi. From 2.1 onwards, I preferred to use Lazarus (+ FPC), in order to make ASuite completely open source.

So it is possible that bugs found in 2.0 do not also exist in 2.1 (unless my possible code errors, of course).

**Comment by megabugman** [comment]
#101 is not fixed in 2.1.0.1280
![not valid](https://user-images.githubusercontent.com/17204819/126559091-6f26e074-0371-4c27-9eb4-deca6f44be55.gif)

Also notice in v2.0 TVirtualStringTree was pre-populated already with two common file extensions
![image](https://user-images.githubusercontent.com/17204819/126559215-808928ff-c241-4b2b-b433-f59387b61a2c.png)

**Comment by salvadorbs** [comment]
Ops... forgot the commit. Now it works in last build: https://github.com/salvadorbs/Asuite/actions/runs/1056657577

**Comment by megabugman** [comment]
perfect. though cannot add * or *.*
not sure if this is an issue anyway. 
closed
