### ISSUE TITLE
[2.0 Beta] Several Bugs

### ISSUE THREAD

**Issue by kkobashi** [salvadorbs/Asuite#53]
Some bugs I ran into on the 2.0 Beta:

- If you set the main window to be always on top, and then turn it off, the behavior is ASuite will still always be on top if you don't shut down and restart ASuite. The change should be immediate.
- All dialog boxes should be centered on the screen. The noted behavior is that you are centering on ASuite itself, not the screen. So if you position ASuite to the left or right hand side of the monitor, the option dialog box (for example) gets clipped or extends to another monitor (on a multi monitor setup). Others like the property, statistics, import, export, scan for files, about, etc. dialog boxes exhibit same behavior.
- Statistics is showing the wrong Windows version on a Windows 10 system. It says Windows 8, which is incorrect. It also shows the wrong build version and shows nothing for Computer name.
- Statistics for drives are showing incorrect numbers for all three components - Used, Free, and Capacity. Compare by doing a right click on a disk drive in Windows File Manager against your statistic numbers. On mine, they are all off significantly.

**Comment by vatterspun** [comment]
Good additions.  I don't know that this project is still underway, but maybe someone else will take up the mantle.

**Comment by salvadorbs** [comment]
1. Unfortunately, you must restart ASuite to apply the change. See https://stackoverflow.com/questions/14872063/why-is-it-not-advisable-to-change-the-formstyle-at-runtime . I will add a message alert to notify it.
2. IMHO, I prefer to open forms at the center of ASuite and not monitor. But I can add an options to change this behaviour in the future.
3. Now fixed with updated 3p components.
4. See above

**Comment by salvadorbs** [comment]
Added new option to open dialog in the center of ASuite Main Form or monitor.
