### ISSUE TITLE
v2.1a graphic menu window is position not saved

### ISSUE THREAD

**Issue by megabugman** [salvadorbs/Asuite#98]
after closing, the window position is not saved. works fine in v2.0

**Comment by salvadorbs** [comment]
it is a known problem and I have already solved it, but the new code needs Lazarus 2.2 (will be released very soon). ASuite 2.1 Alpha 1 was built with Lazarus 2.0.

I leave this issue open, in order to remind us to test the fix once I update ASuite to Lazarus 2.2.

**Comment by megabugman** [comment]
The guys at Lazarus wrote in the 2.2 Release Candidate Log: "Please do not wait for the final release, in order to test. It may be too late. Once the release is out we will have to be more selective about which fixes can be merged for further 2.2.x releases. So it may be, that we can not merge the fix you require. And then you will miss out on all the new features."

-> Hence considering above statement, using 2.2 Release Candidate with an app in alpha stage, should not hurt anyone I guess?
-> Where/How to download the v2.1a nightly builds containing the latest fixes? All I can find is the alpha version from May 18

**Comment by salvadorbs** [comment]
> Hence considering above statement, using 2.2 Release Candidate with an app in alpha stage, should not hurt anyone I guess?
In fact, you are not completely wrong. :)

> Where/How to download the v2.1a nightly builds containing the latest fixes? All I can find is the alpha version from May 18
You can find here: https://github.com/salvadorbs/Asuite/actions

With each commit, ASuite is recompiled via github actions. To date, for example, this is the last compilation made: https://github.com/salvadorbs/Asuite/actions/runs/1045901785

Given the situation, these days I could update the github action workflow to use Lazarus 2.2 instead of version 2.0. I don't know yet if it's better to do it on the Develop branch or do it on a different one.

**Comment by salvadorbs** [comment]
Ok, you can test this issue with last build. Now ASuite is built with Lazarus 2.2 RC1 & FPC 3.2.2.

**Comment by megabugman** [comment]
did not know about github actions. good to know.

the issue is fixed.
